-- RUN THIS IN SUPABASE SQL EDITOR TO ADD CYCLE BAKING COLUMNS
ALTER TABLE members ADD COLUMN IF NOT EXISTS baked_gym_cycles INTEGER DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS baked_trainer_cycles INTEGER DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS legacy_fees NUMERIC DEFAULT 0;
