-- RUN THIS IN SUPABASE SQL EDITOR TO ADD NEW PACKAGE COLUMNS
ALTER TABLE members ADD COLUMN IF NOT EXISTS package_type VARCHAR(50) DEFAULT 'Basic';
ALTER TABLE members ADD COLUMN IF NOT EXISTS trainer_package_type VARCHAR(50) DEFAULT 'none';
ALTER TABLE members ADD COLUMN IF NOT EXISTS has_cardio BOOLEAN DEFAULT false;
ALTER TABLE members ADD COLUMN IF NOT EXISTS trainer_commission NUMERIC DEFAULT 0;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS notes TEXT;
